package com.klemstinegroup.tyrant;

import java.util.HashMap;

public class SavedMaps {
	static public HashMap<String, String> saved = new HashMap<String, String>();
	static {
		saved.put("annevale", "---Tiles---\n" + "aaaaaaabaaaaaaaaaaaa\n"
				+ "aaabaaabbbaaaaaaaaaa\n" + "aabbbbaabbaaaacdddaa\n"
				+ "aaaaabbaabbaacddddaa\n" + "aabbaaaabbaaccdddaaa\n"
				+ "aacccaaabbaaddddedaa\n" + "abccbaabbdaacaddddaa\n"
				+ "accbaaabdaaaaddddcca\n" + "acaaaaeeddaddcacaaaa\n"
				+ "acaeeeeedaadaaaacaaa\n" + "acceaeeedaddaaacaaaa\n"
				+ "aaeeaeedddddaaaacaca\n" + "aaeeaaadddbbdaaaacca\n"
				+ "aaaeeeddddbbbddaaaca\n" + "aacaeedabbbbbbdacaaa\n"
				+ "acaaaadddbbeeebddddd\n" + "aacddddccceeeeaabbca\n"
				+ "accccacaceebeecaccaa\n" + "acaaaaaaaceeecaaacaa\n"
				+ "aaaaaaaaaaaaaaaaaaaa\n" + "---Tiles---\n" + "\n"
				+ "---Legend---\n" + "a = mountains\n" + "b = forests\n"
				+ "c = hills\n" + "d = plains\n" + "e = sea\n"
				+ "---Legend---\n" + "\n" + "---Properties---\n"
				+ "Description = The Annen Vale\n" + "FloorTile = 1\n"
				+ "IsWorldMap = 1\n" + "Level = 10\n"
				+ "MonsterType = IsHostile\n" + "VisionRange = 4\n"
				+ "WallTile = 10\n" + "WanderingRate = 0\n"
				+ "---Properties---\n" + "\n" + "---Things---\n"
				+ "0x0 redistribution point\n" + "0x0 yanthrall temple\n"
				+ "1x0 redistribution point\n" + "1x0 deep dungeon\n"
				+ "2x0 redistribution point\n" + "3x0 redistribution point\n"
				+ "7x0 wilds\n" + "16x4 town\n" + "9x8 dungeon\n"
				+ "7x12 town\n" + "17x12 dungeon\n" + "19x15 karrain\n"
				+ "1x18 grotto\n" + "17x18 mysterious dungeon\n"
				+ "---Things---\n");
		saved.put("doom", "---Tiles---\n" + "aaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaaaaaaa\n" + "aaaaaaabbbbaaaaaaaaa\n"
				+ "aaaaabbbbbbbbbaaaaaa\n" + "aaababbbbbbbabbbaaaa\n"
				+ "aaababbabbbbbbbbaaaa\n" + "aaabbbbbaaaaabbbbaaa\n"
				+ "aaabbaabbaaaabbbbaaa\n" + "aabbbaaaabcccbabbaaa\n"
				+ "aabbbacaabcacaabbaaa\n" + "aabbaacbbbbacaabbbaa\n"
				+ "aabbbbcccccccaabbbaa\n" + "aabbbaaaaacabbabbbaa\n"
				+ "aaabbbaabacaabbbbaaa\n" + "aaabbbbabbcaaabbbaaa\n"
				+ "aaabbbbbbbcabbbbbbaa\n" + "aaaaaabbbbcbbbbbaaaa\n"
				+ "aaaaaaabbbcbbbbaaaaa\n" + "aaaaaaabbbcbbaaaaaaa\n"
				+ "aaaaaaaaaacaaaaaaaaa\n" + "---Tiles---\n" + "\n"
				+ "---Legend---\n" + "a = cave wall\n" + "b = lava sea\n"
				+ "c = stone floor\n" + "---Legend---\n" + "\n"
				+ "---Properties---\n" + "Description = Inside Mount Doom\n"
				+ "FloorTile = 1\n" + "IsWorldMap = 1\n" + "Level = 20\n"
				+ "MonsterType = IsHostile\n" + "WallTile = 10\n"
				+ "WanderingRate = 0\n" + "---Properties---\n" + "\n"
				+ "---Things---\n" + "6x9 dungeon\n" + "10x9 dark tower\n"
				+ "10x19 wilds\n" + "---Things---\n");
		saved.put("wilds", "---Tiles---\n"
				+ "aaaaaaaaabbbbbbbbbbbbbcbbbbbbbbbbbbbbbbb\n"
				+ "abaaaaaaabbbbbbbbbbbbbcbbbbbbbbbbbbbbbbb\n"
				+ "aabaaabaabddbbbddbbbbbdbbbbbbbdddbbbbbbb\n"
				+ "babaaaaebbdbbbbbddbbbddddbbbbbdbbbbbebbb\n"
				+ "aaaaaaaabedeebbbbddbbddbdbbbdddbbbbbbbbb\n"
				+ "bbaaabaabeededebbbdddbdbddbdddddbebbbbbb\n"
				+ "aaaaabaadbddbdebbbbdddddddddbbddbbbebbbb\n"
				+ "aaabaaaadebdbdbbebbbdddddddbbbbbbbbbbbbb\n"
				+ "aaaaaababbddddeebbbbdddddbbbbbebbebebbbb\n"
				+ "aabaaaaaaeebddebbdbbbbdbbbbdbbbbbebbbbbb\n"
				+ "aaaabbbaaaaebbeddddbbbebbddddebebeebbbbb\n"
				+ "abbbbbbbbaaabbbddddbbdddddbdbddeebdebbbb\n"
				+ "bbbbbbbebbaaaeedddddddddbdddddddbdddbeeb\n"
				+ "bbbbbbbbaaaaaadbddeddbebddddbddddddddbbb\n"
				+ "bbbbbbfbaaaaaaabddbdddbbbbbbbbbdddddbbbb\n"
				+ "bbfffffbbabaaaaabddddddebbbbbbdbdddddbbb\n"
				+ "bbffbffffaabbaaaadbdedbbbebbbeddddedbbbb\n"
				+ "bbfffffbfbbbaaaaabbdebdebbbbeddbbbebebbb\n"
				+ "bbfffbffffbbaaaaaaadbbebbbbbeebbebbbbbbb\n"
				+ "bfffffffffbbbaaaaaabfbbbbbbbbbbbbbbbbbbb\n"
				+ "bbfffbbffbbbbbafffffdfbbbbbbbbbbbbbbbbbb\n"
				+ "bbbfffffbbbbbeffbbfffbfbbbbbbbbbbgbbbbbb\n"
				+ "bbbfffbbeebbbefbbfbfdfdbbbbbbbbgggbbbbbb\n"
				+ "bbfbfffffbbffeffffffbbbbbbbbggggggbbbbbb\n"
				+ "bbbfffbfebdfffbffffdbfbbbbbggbbggbbbbbbb\n"
				+ "bbffffffffffffffbfffffbbbdggbbbggbbbbbbb\n"
				+ "bbfffffbbeffffffffffdbddddddbbbgbbbbbbbb\n"
				+ "bbfffffbbdbffffffffdffddddddddbgbbbbbbbb\n"
				+ "bbffbfbeebbfffffffffffddddddddbgbbbbbbbb\n"
				+ "bbbfffbbefffdfffffffeddddbdbbdggbbbbbbbb\n"
				+ "bbbfbfbbeebdffffbeefbddddbbbbdgbbbbbbbbb\n"
				+ "bbbbbbaabebbfffefefffbddddbdfdbbbbbbbbbb\n"
				+ "bbfbaaabbeeffebbffbdffddddbdbdbbbbbbbbbb\n"
				+ "bfaaaabbbbbbdefbfbbbddbbddddbbbbbbbbbbbb\n"
				+ "aaaaddabaabebbdbbbdddddddddbbbbbbbbbbbbb\n"
				+ "aaaaadaaaaaabeeebbbbddddddbbbbbbbbbbbbbb\n"
				+ "bffaaaaaaaaaaabebbbbbbddbbbbbbbbbbbbbbbb\n"
				+ "bbffffaaabfbfbbbbbbbbbddbbbbbbbbbbbbbbbb\n"
				+ "bbbbffffffbbbbbbbbbbbbbdbbbbbbbbbbbbbbbb\n"
				+ "bbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbbbbbbbbbb\n"
				+ "---Tiles---\n" + "\n" + "---Legend---\n" + "a = sea\n"
				+ "b = mountains\n" + "c = stone floor\n" + "d = plains\n"
				+ "e = hills\n" + "f = forests\n" + "g = lava sea\n"
				+ "---Legend---\n" + "\n" + "---Properties---\n"
				+ "Description = The Northern Wilds\n" + "FloorTile = 1\n"
				+ "IsWorldMap = 1\n" + "Level = 15\n"
				+ "MonsterType = IsHostile\n" + "WallTile = 10\n"
				+ "WanderingRate = 0\n" + "---Properties---\n" + "\n"
				+ "---Things---\n" + "0x0 redistribution point\n"
				+ "1x0 redistribution point\n" + "2x0 redistribution point\n"
				+ "3x0 redistribution point\n" + "4x0 redistribution point\n"
				+ "5x0 redistribution point\n" + "6x0 redistribution point\n"
				+ "22x0 doom\n" + "34x21 firetop\n" + "23x39 annenvale\n"
				+ "---Things---\n");
		saved.put("yanthrall", "---Tiles---\n"
				+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaabbbbaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaabbbcbbaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaabbbbaabbccccbbabbbbaaaaaaaaaaaaaaaa\n"
				+ "aaaaaabbccbbbbccccccbbbccbbaaaabbbbbaaaaaa\n"
				+ "aaaaabbcccccbbccccccbbccccbbabbbaaabbbaaaa\n"
				+ "aaaaabccccccbbbcccbbbccccccbbbaaaaaaabbaaa\n"
				+ "aaaabbccccccbabbcbbccccccccbaaaaaaaaaabbaa\n"
				+ "aaaabcccccccbaabcccccccccccbaaaaaaaaaaabaa\n"
				+ "aaaabcccccccbbbbcccccccccccbbbaadddaaaabaa\n"
				+ "aaaabbccccccccccccccccccccbbcbbaddddaaabaa\n"
				+ "aaaabbbccccbbccbbbbbbbcbbbbcccbaaaaaaaabaa\n"
				+ "aaaaaabbbbcbcccbcccccbccccccccbaaaaaaaabaa\n"
				+ "aaaaaaabcccccbbbcccccbbbbbccccbaaaaaaaabaa\n"
				+ "aaaaabbbbcccbbcccccccccbbbcccbbabbbbbbbbaa\n"
				+ "aaabbbccbccbbcccccccccccbbccbbaaaaaeeeebaa\n"
				+ "aabbbcccbccbcccccccccccccbbbbaaaaaaeffebaa\n"
				+ "abbbbcccbccccccccccccccccbccbbaaaaaeffebaa\n"
				+ "abccbcbbbccbcccccccccccccbcccbbaaaaeffebaa\n"
				+ "abcccccccccbccccccccccccccccccbaaaaeffebaa\n"
				+ "abccbcbbbcbbbcccccccccccbbccccbaaaafffebaa\n"
				+ "abbbbcccbcccbcccccccccccbccccccaaaaeffebaa\n"
				+ "aabbbcccbcccbcccccccccccbcccccbaaaaeeeebaa\n"
				+ "aaabbbccbcccbbcccccccccbbcccccbaaaaaaaabaa\n"
				+ "aaaaabbbbbbcbbcccccccccbcccccbbaaaaaaaabaa\n"
				+ "aaaaaaaaaabccbbcccccccbbccccbbaaaaaaaaabaa\n"
				+ "aaaaaaaaggbgccbbcccccbbcccbbbaaaaaaaaaabaa\n"
				+ "aaaaaaggggbgccbbbbcbbbbcccbgggfgaaaaaaabaa\n"
				+ "gggafgggbbbbccbbbcccbbbbbcbbbgfggaaaaabbaa\n"
				+ "ggggfgabbccbbcbbbcccbbbbccccbbaaggaaabbaaa\n"
				+ "aaaaaaabccccccbbbbcbbbbccccccbbbbgbbbbaaaa\n"
				+ "aaaaaaabccccccbbcccccbbccccccbaaagggaaaaaa\n"
				+ "aaaaaaabbccccbbacccccabbccccbbaaaaaggggggg\n"
				+ "aaaaaaaabbccbbaaacccaaabbccbbaaaaaaaaagggg\n"
				+ "aaaaaaaaabbbbaaaaaaaaaaabbbbaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
				+ "---Tiles---\n" + "\n" + "---Legend---\n" + "a = grass\n"
				+ "b = stone wall\n" + "c = stone floor\n" + "d = pool\n"
				+ "e = wooden wall\n" + "f = wooden floor\n" + "g = stream\n"
				+ "---Legend---\n" + "\n" + "---Properties---\n"
				+ "Description = Temple of Yanthrall\n" + "FloorTile = 1\n"
				+ "Level = 20\n" + "MonsterType = IsHostile\n"
				+ "WallTile = 10\n" + "WanderingRate = 0\n"
				+ "---Properties---\n" + "\n" + "---Things---\n"
				+ "1x2 thorny bush\n" + "5x2 blueberry bush\n"
				+ "8x2 blueberry bush\n" + "12x2 blueberry bush\n"
				+ "23x2 thorny bush\n" + "26x2 thorny bush\n"
				+ "5x3 thorny bush\n" + "11x3 thorny bush\n"
				+ "31x3 thorny bush\n" + "0x4 thick bush\n"
				+ "2x4 blueberry bush\n" + "3x4 thick bush\n" + "24x6 stool\n"
				+ "0x7 blueberry bush\n" + "3x7 thick bush\n" + "23x7 stool\n"
				+ "24x7 table\n" + "25x7 stool\n" + "16x8 strong door\n"
				+ "22x8 stool\n" + "24x8 stool\n" + "32x8 bush\n"
				+ "34x8 bush\n" + "2x9 thorny bush\n" + "18x9 stool\n"
				+ "20x9 stool\n" + "22x9 table\n" + "23x9 stool\n"
				+ "24x9 stool\n" + "30x9 bush\n" + "36x9 bush\n"
				+ "17x10 stool\n" + "18x10 table\n" + "19x10 stool\n"
				+ "20x10 table\n" + "21x10 stool\n" + "23x10 stool\n"
				+ "24x10 table\n" + "25x10 stool\n" + "1x11 blueberry bush\n"
				+ "12x11 strong door\n" + "15x11 warning point\n"
				+ "15x11 strong door\n" + "20x11 stool\n" + "24x11 stool\n"
				+ "37x11 bush\n" + "3x12 blueberry bush\n"
				+ "22x12 strong door\n" + "10x13 strong door\n"
				+ "16x13 fire\n" + "17x13 fire\n" + "18x13 golden altar\n"
				+ "19x13 fire\n" + "20x13 fire\n" + "32x13 bush\n"
				+ "34x13 bush\n" + "36x13 bush\n" + "16x14 stone altar\n"
				+ "20x14 stone altar\n" + "14x15 stone altar\n"
				+ "22x15 stone altar\n" + "31x15 invincible portcullis\n"
				+ "0x16 blueberry bush\n" + "20x16 blood guard\n"
				+ "10x17 guard point\n" + "10x17 blood guard\n"
				+ "12x17 guard point\n" + "12x17 blood guard\n"
				+ "11x18 warning point\n" + "11x18 strong door\n"
				+ "15x18 guard point\n" + "15x18 stool\n"
				+ "15x18 village girl\n" + "16x18 guard point\n"
				+ "16x18 stool\n" + "16x18 townie\n" + "17x18 guard point\n"
				+ "17x18 stool\n" + "17x18 townie\n" + "19x18 guard point\n"
				+ "19x18 stool\n" + "19x18 village girl\n"
				+ "20x18 guard point\n" + "20x18 stool\n" + "20x18 townie\n"
				+ "21x18 guard point\n" + "21x18 stool\n"
				+ "21x18 townswoman\n" + "33x18 ranger\n"
				+ "5x19 strong door\n" + "10x19 guard point\n"
				+ "10x19 blood guard\n" + "12x19 guard point\n"
				+ "12x19 blood guard\n" + "15x19 guard point\n"
				+ "15x19 stool\n" + "15x19 village girl\n"
				+ "16x19 guard point\n" + "16x19 stool\n"
				+ "16x19 townswoman\n" + "17x19 guard point\n"
				+ "17x19 stool\n" + "17x19 townie\n" + "19x19 guard point\n"
				+ "19x19 stool\n" + "19x19 townie\n" + "20x19 guard point\n"
				+ "20x19 stool\n" + "20x19 townswoman\n"
				+ "21x19 guard point\n" + "21x19 stool\n"
				+ "21x19 village girl\n" + "24x19 guard point\n"
				+ "24x19 blood guard\n" + "26x19 guard point\n"
				+ "26x19 blood guard\n" + "31x19 potted flower\n"
				+ "4x20 strong door\n" + "14x20 blood guard\n"
				+ "15x20 stool\n" + "15x20 ranger\n" + "16x20 guard point\n"
				+ "16x20 stool\n" + "16x20 village girl\n"
				+ "17x20 guard point\n" + "17x20 stool\n"
				+ "17x20 village girl\n" + "19x20 guard point\n"
				+ "19x20 stool\n" + "19x20 village girl\n"
				+ "20x20 guard point\n" + "20x20 stool\n"
				+ "20x20 village girl\n" + "21x20 stool\n"
				+ "25x20 warning point\n" + "25x20 strong door\n"
				+ "31x20 potted flower\n" + "34x20 potted flower\n"
				+ "5x21 strong door\n" + "9x21 strong door\n" + "16x21 stool\n"
				+ "17x21 guard point\n" + "17x21 stool\n" + "17x21 ranger\n"
				+ "19x21 stool\n" + "20x21 stool\n" + "22x21 blood guard\n"
				+ "26x21 guard point\n" + "26x21 blood guard\n"
				+ "35x21 unbreakable door\n" + "16x22 stool\n"
				+ "17x22 stool\n" + "19x22 stool\n" + "20x22 stool\n"
				+ "30x22 warning point\n" + "30x22 strong door\n"
				+ "34x22 potted flower\n" + "21x23 guard\n" + "20x24 dwarf\n"
				+ "31x24 potted flower\n" + "11x25 strong door\n"
				+ "31x25 potted flower\n" + "0x26 blueberry bush\n"
				+ "35x26 ranger\n" + "37x26 blueberry bush\n"
				+ "30x27 blueberry bush\n" + "36x27 blueberry bush\n"
				+ "2x28 blueberry bush\n" + "5x28 blueberry bush\n"
				+ "18x28 warning point\n" + "37x28 blueberry bush\n"
				+ "3x29 blueberry bush\n" + "17x29 guard point\n"
				+ "17x29 blood guard\n" + "19x29 guard point\n"
				+ "19x29 blood guard\n" + "25x29 strong door\n"
				+ "36x29 blueberry bush\n" + "9x30 [IsFood]\n"
				+ "10x30 [IsFood]\n" + "13x30 strong door\n"
				+ "31x30 blueberry bush\n" + "35x30 blueberry bush\n"
				+ "8x31 [IsFood]\n" + "9x31 [IsFood]\n" + "10x31 [IsFood]\n"
				+ "11x31 [IsFood]\n" + "12x31 [IsFood]\n" + "13x31 [IsFood]\n"
				+ "18x31 warning point\n" + "24x31 blood guard\n"
				+ "26x31 blood guard\n" + "33x31 invincible portcullis\n"
				+ "1x32 blueberry bush\n" + "4x32 blueberry bush\n"
				+ "8x32 [IsFood]\n" + "9x32 [IsFood]\n" + "10x32 [IsFood]\n"
				+ "11x32 [IsFood]\n" + "12x32 [IsFood]\n" + "13x32 [IsFood]\n"
				+ "17x32 guard point\n" + "17x32 blood guard\n"
				+ "19x32 guard point\n" + "19x32 blood guard\n"
				+ "25x32 guard point\n" + "25x32 blood guard\n"
				+ "9x33 [IsFood]\n" + "10x33 [IsFood]\n" + "11x33 [IsFood]\n"
				+ "12x33 [IsFood]\n" + "24x33 blood guard\n"
				+ "26x33 blood guard\n" + "10x34 [IsFood]\n"
				+ "11x34 [IsFood]\n" + "15x34 menhir\n" + "21x34 menhir\n"
				+ "26x34 blood guard\n" + "2x35 blueberry bush\n"
				+ "15x36 menhir\n" + "21x36 menhir\n" + "1x37 blueberry bush\n"
				+ "15x38 menhir\n" + "21x38 menhir\n" + "15x40 menhir\n"
				+ "21x40 menhir\n" + "18x41 entrance point\n"
				+ "---Things---\n");
		saved.put("firetop", "---Tiles---\n" + "aaaaaaaaaaaaaaaaaaaa\n"
				+ "aabbbbbbbbabbbbabbba\n" + "aabbbbbbbbabbbbabbba\n"
				+ "aabbbbbbbbabbbbabbba\n" + "aabbbbbbbbaabaaabbba\n"
				+ "aabbbbbbbbabbbbbbbba\n" + "aaaaaaaabbabbbbbbbba\n"
				+ "abbbbbbabbbbbbbbbaaa\n" + "abbbbbbabbabbbbbbacc\n"
				+ "aaaaaaaabbaaaaaaaacc\n" + "abbabbbabbabbbbbbbcc\n"
				+ "abbabbbabbabbbbbbbcc\n" + "abbbbbbbbbbbbbbbbbcc\n"
				+ "aababbbabbabbbabaacc\n" + "abbabbbabbabbaabbaac\n"
				+ "abbabbbabbabbabbbbac\n" + "abbaabaabbaaaabbbbac\n"
				+ "abbadddabbaddaabbaac\n" + "aaaaddddbbddddabaadc\n"
				+ "aaadddddbbdddddddddc\n" + "aaddddddbbddedddddac\n"
				+ "aaddddddbbeeedddddcc\n" + "aaddddddbbddddddddcd\n"
				+ "aadddddddeeddeddddcd\n" + "aaaddddefedddddddaca\n"
				+ "aaaadeeedddeddedaaca\n" + "aaaaedddfeddddedaaca\n"
				+ "aaaaddeeffdfededdaca\n" + "aaaaddeefddddddddccd\n"
				+ "aaadddddfeefdddedced\n" + "ddddddeedddddddedcdd\n"
				+ "ddddddeeddfdeddddcde\n" + "dddddeedddddfffddcdd\n"
				+ "dddddddddddddeedfcdd\n" + "ddddeddddddeeddddcde\n"
				+ "ddddeddddddddddeecee\n" + "ddddddeddddefeeeffee\n"
				+ "dddddddddeeefeeffffe\n" + "ddddddddeefffeeffffe\n"
				+ "dddddddeeffffffffffe\n" + "dddddddeefffffeffffe\n"
				+ "dddddddeffffffeffffe\n" + "dddddddeffffffeffffe\n"
				+ "eddddddeefffffeffffe\n" + "eedddddeeefffeeeefee\n"
				+ "eeedddddeefffeeeeeee\n" + "eeeedddddeffefeeeeee\n"
				+ "eeeeeddddfffffeefffe\n" + "eeeeeddddfefffeffffe\n"
				+ "eeeeeddddfffffeffffe\n" + "eeeeedddeefffeeffffe\n"
				+ "eeeeedddeefefeeffeee\n" + "eeeeedddeeffffeeeeee\n"
				+ "eeeeedddeeffffeeeeed\n" + "eeeeddddeeefffeeeeed\n"
				+ "eeeedddeeeeffeeeeedd\n" + "eeeddddeeeffffeeeedd\n"
				+ "eeddddeeeeffffeeeedd\n" + "eeddddeeeeffffeeeddd\n"
				+ "eedddeeeefffffeedddd\n" + "eedddeeeeffffddddddd\n"
				+ "eedddeefffffdddddddd\n" + "eedddeeffffdddddddde\n"
				+ "eedddeeeccddddddddee\n" + "eedddeddcccdddddeeee\n"
				+ "eedddddddcccddeeeeee\n" + "eeddddddddccfeeeeeee\n"
				+ "eedddddddeefffeeeeee\n" + "eeedddddeeeeffeeeeee\n"
				+ "eeeddddeeeeeffeeeeee\n" + "eeeddddeeeeeefeeeeee\n"
				+ "eeedddddeeeeefeeeeee\n" + "eeedddddeeeeffeeeeee\n"
				+ "eeeedddddeeeffeeeeee\n" + "eeeedddddeefffeeeeee\n"
				+ "eeeeeddddfefffeeeeee\n" + "eeeeeedddfffffeeeeee\n"
				+ "eeeeeeeddfffddeeeeee\n" + "eeeeeeeddfffddeeeeee\n"
				+ "eeeeeeedddfdddeeeeee\n" + "---Tiles---\n" + "\n"
				+ "---Legend---\n" + "a = metal wall\n" + "b = red floor\n"
				+ "c = stone floor\n" + "d = lava\n" + "e = cave wall\n"
				+ "f = cave floor\n" + "---Legend---\n" + "\n"
				+ "---Properties---\n" + "Description = Firetop Mountain\n"
				+ "FloorTile = 1\n" + "Level = 33\n"
				+ "MonsterType = IsDragon\n" + "WallTile = 10\n"
				+ "WanderingRate = 100\n" + "---Properties---\n" + "\n"
				+ "---Things---\n" + "2x2 red dragon\n" + "9x2 red dragon\n"
				+ "5x3 black dragon\n" + "12x4 golden portcullis\n"
				+ "   KeyName = brass key\n" + "2x6 secret door\n"
				+ "12x6 black dragon\n" + "1x7 frost dragon\n"
				+ "4x7 red dragon\n" + "5x7 black dragon\n"
				+ "6x7 artifact point\n" + "10x7 trapped black door\n"
				+ "   KeyName = dull key\n" + "14x7 red dragon\n"
				+ "1x8 artifact point\n" + "2x8 blue dragon\n"
				+ "3x8 blue dragon\n" + "4x8 frost dragon\n"
				+ "5x8 red dragon\n" + "6x8 black dragon\n"
				+ "3x12 trapped black door\n" + "   KeyName = copper key\n"
				+ "7x12 trapped black door\n" + "   KeyName = copper key\n"
				+ "10x12 enchanted door\n" + "   KeyName = iron key\n"
				+ "2x13 trapped black door\n" + "   KeyName = copper key\n"
				+ "15x13 enchanted door\n" + "   KeyName = brass key\n"
				+ "1x14 frost dragon\n" + "2x14 frost dragon\n"
				+ "1x15 frost dragon\n" + "2x15 frost dragon\n"
				+ "4x15 red dragon\n" + "1x16 frost dragon\n"
				+ "2x16 frost dragon\n" + "5x16 invincible portcullis\n"
				+ "   KeyName = skull key\n" + "1x17 frost dragon\n"
				+ "2x17 frost dragon\n" + "8x17 trapped black door\n"
				+ "   KeyName = iron key\n" + "9x17 trapped black door\n"
				+ "   KeyName = bronze key\n" + "15x17 red dragon\n"
				+ "15x18 invincible portcullis\n" + "   KeyName = golden key\n"
				+ "5x22 red dragon\n" + "14x22 red dragon\n"
				+ "18x24 trapped black door\n" + "   KeyName = golden key\n"
				+ "18x25 red dragon\n" + "18x26 red dragon\n"
				+ "18x27 trapped black door\n" + "   KeyName = ornate key\n"
				+ "13x28 red dragon\n" + "4x29 red dragon\n"
				+ "14x39 trapped black door\n" + "   KeyName = golden key\n"
				+ "11x40 red dragon\n" + "17x40 frost dragon\n"
				+ "18x40 frost dragon\n" + "17x41 blue dragon\n"
				+ "16x47 skeletal dragon\n" + "17x47 fearsome skeleton\n"
				+ "18x47 fearsome skeleton\n" + "14x48 secret door\n"
				+ "15x48 skeleton hero\n" + "16x48 skeletal dragon\n"
				+ "17x48 fearsome skeleton\n" + "18x48 artifact point\n"
				+ "15x49 skeleton hero\n" + "16x49 skeletal dragon\n"
				+ "17x49 skeleton lord\n" + "18x49 fearsome skeleton\n"
				+ "15x50 skeleton hero\n" + "16x50 horrendous zombie\n"
				+ "17x50 skeleton lord\n" + "18x50 fearsome skeleton\n"
				+ "15x51 horrendous zombie\n" + "16x51 horrendous zombie\n"
				+ "12x53 blue dragon\n" + "13x58 blue dragon\n"
				+ "9x60 green dragon\n" + "11x61 blue dragon\n"
				+ "12x69 green dragon\n" + "10x79 entrance point\n"
				+ "---Things---\n");
		saved.put("grotto", "---Tiles---\n" + "aaaaaaaaaaaaaaaaaaaa\n"
				+ "aaabbaaaaaaaaaaaaaaa\n" + "aabbaabbbaaaaaccccca\n"
				+ "aabaabbbbbaaacccccca\n" + "abbabbbbbbaaacccccca\n"
				+ "abbabbbbbbaaaaccccca\n" + "abbaabbbbbbaaaaaacca\n"
				+ "aabaaabaabbbaaddacca\n" + "abbabbbbaabbbdddaaca\n"
				+ "abbabbbbbaabbdddccca\n" + "abbaabbbbbabbdddccca\n"
				+ "abbbaaaaaaabbdddccca\n" + "aabbaabbaaabbbddaaca\n"
				+ "aaabbbbbbaabbbddccca\n" + "aaabbdddbbebeaaaaaca\n"
				+ "aaaaaddddbebeefffcca\n" + "eeeeeeeeeeebeeeffcca\n"
				+ "ebbebbbbebbbbbeaccca\n" + "ebbebbbbbbbbbbecccca\n"
				+ "ebbebbbbebbbbbeaaaca\n" + "ebbeabbbebbbbbecccca\n"
				+ "ebbebbbbebbbbbecccca\n" + "eeeeebeeeeebeeeeccca\n"
				+ "ebbbbbbbbbbbbbbeaaca\n" + "ebbbbbbbbbbbbbbeaaca\n"
				+ "eeeeceeeeeeebeeeeeca\n" + "eccccccebbbbbbbbbeca\n"
				+ "eccececebbbbbbbbbeca\n" + "eccccccebebbbbbebeca\n"
				+ "eccccccbbbbbbbbbbeca\n" + "eccccccebebbbbbebeca\n"
				+ "eeeeceeebbbbbbbbbeca\n" + "eccccccebebbbbbebeca\n"
				+ "eccccccbbbbbbbbbbeca\n" + "eccccccebebbbbbebeca\n"
				+ "eccccccebbbbbbbbbeca\n" + "ecccccceeeeebeeeeeca\n"
				+ "eeeeceeeaaaabaaaaaca\n" + "ecccccceaabbbbabbaba\n"
				+ "eccgggceaabbbbabbaaa\n" + "eccgggceaaaabbbbbbba\n"
				+ "ecccccceaaaabbbbbbba\n" + "hhhhchhhhhaaabbbbbba\n"
				+ "hiiiiiiiihaaaabbbbba\n" + "hiiiiiiiihabaaabbbaa\n"
				+ "hiiiiiiiihabbbabaaaa\n" + "hiiiiiiiihabbbbbaaaa\n"
				+ "hiiiiiiiihabbbaaaaaa\n" + "hiiiiiiiihaabbaaaaaa\n"
				+ "hhhhhhhhhhaaaaaaaaaa\n" + "---Tiles---\n" + "\n"
				+ "---Legend---\n" + "a = cave wall\n" + "b = floor\n"
				+ "c = stone floor\n" + "d = lava\n" + "e = stone wall\n"
				+ "f = pool\n" + "g = river\n" + "h = metal wall\n"
				+ "i = red floor\n" + "---Legend---\n" + "\n"
				+ "---Properties---\n" + "Description = Goblin Grotto\n"
				+ "FloorTile = 1\n" + "Level = 8\n"
				+ "MonsterType = IsHostile\n" + "WanderingRate = 300\n"
				+ "---Properties---\n" + "\n" + "---Things---\n"
				+ "3x1 [IsUndead]\n" + "4x1 [IsUndead]\n" + "2x2 [IsUndead]\n"
				+ "3x2 [IsUndead]\n" + "2x3 [IsUndead]\n"
				+ "8x3 entrance point\n" + "1x4 [IsUndead]\n"
				+ "2x4 [IsUndead]\n" + "5x4 entrance point\n"
				+ "15x4 goblin hero\n" + "1x5 [IsUndead]\n"
				+ "2x5 [IsUndead]\n" + "1x6 [IsUndead]\n" + "2x6 [IsUndead]\n"
				+ "2x7 stone door\n" + "   KeyName = golden key\n"
				+ "6x7 trapped black door\n" + "   KeyName = golden key\n"
				+ "3x8 secret door\n" + "4x8 [IsGoblinoid]\n"
				+ "5x8 [IsGoblinoid]\n" + "7x8 [IsBandit]\n" + "18x8 door\n"
				+ "   KeyName = bronze key\n" + "1x9 [IsGoblinoid]\n"
				+ "2x9 [IsGoblinoid]\n" + "4x9 [IsGoblinoid]\n"
				+ "5x9 [IsGoblinoid]\n" + "7x9 [IsBandit]\n"
				+ "8x9 [IsBandit]\n" + "16x9 goblin archer\n"
				+ "17x9 goblin rockthrower\n" + "18x9 goblin archer\n"
				+ "1x10 [IsGoblinoid]\n" + "2x10 [IsGoblinoid]\n"
				+ "5x10 [IsGoblinoid]\n" + "6x10 blue imp\n"
				+ "7x10 [IsBandit]\n" + "8x10 [IsBandit]\n"
				+ "9x10 [IsBandit]\n" + "16x10 goblin archer\n"
				+ "17x10 goblin chieftain\n" + "18x10 goblin archer\n"
				+ "2x11 [IsGoblinoid]\n" + "3x11 [IsGoblinoid]\n"
				+ "16x11 goblin archer\n" + "17x11 goblin rockthrower\n"
				+ "18x11 goblin shaman\n" + "2x12 [IsGoblinoid]\n"
				+ "3x12 [IsGoblinoid]\n" + "6x12 healing salve\n"
				+ "7x12 healing salve\n" + "18x12 trapped black door\n"
				+ "   KeyName = ornate key\n" + "4x13 Fireball trap\n"
				+ "5x13 Teleport Monster trap\n"
				+ "6x13 Teleport Monster trap\n" + "7x13 blindness trap\n"
				+ "8x13 curse trap\n" + "16x13 invincible portcullis\n"
				+ "   KeyName = iron key\n" + "3x14 weedy goblin\n"
				+ "4x14 Fireball trap\n" + "8x14 healing salve\n"
				+ "9x14 potion of cure poison\n"
				+ "18x14 invisible riddle door\n" + "   KeyName = copper key\n"
				+ "11x15 trapped black door\n" + "   KeyName = copper key\n"
				+ "8x18 door\n" + "   KeyName = copper key\n"
				+ "3x19 secret door\n" + "5x22 door\n"
				+ "   KeyName = bronze key\n" + "11x22 door\n"
				+ "   KeyName = bronze key\n" + "18x23 rotten door\n"
				+ "   KeyName = brass key\n" + "4x25 door\n"
				+ "   KeyName = copper key\n" + "12x25 strong door\n"
				+ "   KeyName = iron key\n" + "1x26 goblin archer\n"
				+ "2x26 goblin archer\n" + "3x26 invincible portcullis\n"
				+ "   KeyName = bronze key\n" + "5x26 invincible portcullis\n"
				+ "   KeyName = dull key\n" + "6x26 goblin archer\n"
				+ "1x27 goblin archer\n" + "2x27 goblin archer\n"
				+ "4x27 invisible riddle door\n" + "   KeyName = copper key\n"
				+ "6x27 goblin chieftain\n" + "1x28 goblin archer\n"
				+ "2x28 goblin archer\n" + "3x28 goblin archer\n"
				+ "4x28 goblin archer\n" + "5x28 goblin archer\n"
				+ "6x28 goblin chieftain\n" + "1x29 goblin archer\n"
				+ "2x29 goblin archer\n" + "3x29 flying goblin\n"
				+ "4x29 flying goblin\n" + "5x29 flying goblin\n"
				+ "6x29 flying goblin\n" + "7x29 door\n"
				+ "   KeyName = brass key\n" + "1x30 goblin archer\n"
				+ "2x30 goblin archer\n" + "3x30 flying goblin\n"
				+ "4x30 flying goblin\n" + "5x30 flying goblin\n"
				+ "6x30 flying goblin\n" + "4x31 door\n"
				+ "   KeyName = copper key\n" + "8x31 goblin archer\n"
				+ "16x31 goblin archer\n" + "8x32 goblin archer\n"
				+ "16x32 goblin archer\n" + "7x33 door\n"
				+ "   KeyName = bronze key\n" + "8x33 goblin archer\n"
				+ "10x33 big orc\n" + "11x33 big orc\n" + "12x33 big orc\n"
				+ "13x33 big orc\n" + "14x33 big orc\n"
				+ "16x33 goblin archer\n" + "18x33 big goblin\n"
				+ "10x34 goblin shaman\n" + "11x34 orc warrior\n"
				+ "12x34 orc warrior\n" + "13x34 orc warrior\n"
				+ "14x34 goblin shaman\n" + "18x34 big goblin\n"
				+ "12x35 orc champion\n" + "18x35 big goblin\n"
				+ "12x36 door\n" + "   KeyName = copper key\n"
				+ "18x36 big goblin\n" + "4x37 door\n"
				+ "   KeyName = brass key\n" + "18x37 rotten door\n"
				+ "   KeyName = brass key\n" + "10x38 [IsUndead]\n"
				+ "11x38 [IsUndead]\n" + "12x38 [IsUndead]\n"
				+ "13x38 [IsUndead]\n" + "17x38 secret door\n"
				+ "10x39 [IsUndead]\n" + "11x39 small gravestone\n"
				+ "13x39 [IsUndead]\n" + "15x39 gravestone\n"
				+ "16x39 gravestone\n" + "2x40 crocodile\n"
				+ "6x40 crocodile\n" + "13x40 [IsUndead]\n"
				+ "14x40 [IsUndead]\n" + "15x40 [IsUndead]\n"
				+ "16x40 [IsUndead]\n" + "2x41 ralkan\n" + "3x41 ralkan\n"
				+ "4x41 crocodile\n" + "5x41 ralkan\n" + "6x41 ralkan\n"
				+ "12x41 gravestone\n" + "13x41 [IsUndead]\n"
				+ "14x41 [IsUndead]\n" + "15x41 gravestone\n"
				+ "16x41 [IsUndead]\n" + "4x42 door\n"
				+ "   KeyName = brass key\n" + "14x42 [IsUndead]\n"
				+ "15x42 [IsUndead]\n" + "16x42 [IsUndead]\n"
				+ "17x42 small gravestone\n" + "18x42 gravestone\n"
				+ "1x43 copper coin\n" + "2x43 silver coin\n"
				+ "3x43 copper coin\n" + "4x43 silver coin\n"
				+ "5x43 copper coin\n" + "6x43 copper coin\n"
				+ "7x43 silver coin\n" + "8x43 copper coin\n"
				+ "15x43 small gravestone\n" + "16x43 [IsUndead]\n"
				+ "17x43 [IsUndead]\n" + "1x44 silver coin\n"
				+ "2x44 silver coin\n" + "3x44 silver coin\n"
				+ "4x44 copper coin\n" + "5x44 silver coin\n"
				+ "6x44 copper coin\n" + "7x44 silver coin\n"
				+ "8x44 silver coin\n" + "11x44 [IsPotion]\n"
				+ "15x44 [IsUndead]\n" + "16x44 [IsUndead]\n"
				+ "17x44 [IsUndead]\n" + "1x45 gold coin\n"
				+ "2x45 gold coin\n" + "3x45 silver coin\n"
				+ "4x45 copper coin\n" + "5x45 copper coin\n"
				+ "6x45 silver coin\n" + "7x45 silver coin\n"
				+ "8x45 sovereign\n" + "11x45 [IsPotion]\n"
				+ "12x45 [IsPotion]\n" + "13x45 [IsPotion]\n"
				+ "15x45 small gravestone\n" + "1x46 sovereign\n"
				+ "2x46 gold coin\n" + "3x46 silver coin\n"
				+ "4x46 silver coin\n" + "5x46 silver coin\n"
				+ "6x46 gold coin\n" + "7x46 sovereign\n" + "8x46 sovereign\n"
				+ "11x46 [IsPotion]\n" + "12x46 [IsPotion]\n"
				+ "13x46 [IsPotion]\n" + "14x46 door\n"
				+ "   KeyName = bronze key\n" + "1x47 sovereign\n"
				+ "2x47 gold coin\n" + "3x47 gold coin\n" + "4x47 gold coin\n"
				+ "5x47 gold coin\n" + "6x47 gold coin\n" + "7x47 sovereign\n"
				+ "8x47 sovereign\n" + "11x47 [IsPotion]\n"
				+ "12x47 [IsPotion]\n" + "13x47 [IsPotion]\n"
				+ "1x48 sovereign\n" + "2x48 sovereign\n" + "3x48 sovereign\n"
				+ "4x48 sovereign\n" + "5x48 sovereign\n" + "6x48 sovereign\n"
				+ "7x48 sovereign\n" + "8x48 sovereign\n"
				+ "12x48 [IsPotion]\n" + "13x48 [IsPotion]\n"
				+ "---Things---\n");
		saved.put("woodfort", "---Tiles---\n"
				+ "aaaaaaaaaaaaaaaabbbbaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaabbbbaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaaabbbaaaaaaaaaaaa\n"
				+ "aaaaaaaaacaaabbbbbaaaaaaaacaaa\n"
				+ "acaaaaaaaaaaabbbbbcaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaabbbbbbaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaddddbbbbaaaaaaaaaaa\n"
				+ "aaaaaacaaaddaaddbbbaaaddddaaaa\n"
				+ "aaaaaaaaaadaaaadbbbaacdaadaaaa\n"
				+ "aaaaaaaaaadaaaddddddaadaadaaaa\n"
				+ "aaaaaaaaaaddaadaaaadaadaddcaaa\n"
				+ "aaaaaaaaacaddddaaaadaaaaadaaaa\n"
				+ "aaaaaaaaaccaaaddaaddaaaaadddda\n"
				+ "aaaaaacaaaaaaaaaaaaaaaaaaaaada\n"
				+ "aacaaaaaaaaaaaaaaaaaaaaaadaada\n"
				+ "aaaaaaaaaaaaaaddddddacaaadddda\n"
				+ "aaaaaaacaaaaaadabbaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaacadabbadaaaaaacaaa\n"
				+ "aaaaaaaaaaaddddabbadaaaaaaddda\n"
				+ "aacaaaaaaaddaaaabbadaaaaaaaada\n"
				+ "aaaaaacaaadaaadddddddddddddada\n"
				+ "aaaaaaaaaadaaaadbbaaadaaaaddda\n"
				+ "aaaaaaaaaaddaaddbbaaaaaaaaadaa\n"
				+ "aacaaaaaaaaddddabbaaadaaaaadaa\n"
				+ "caaaaaaaaaaaaaaabaaaadaaaaadaa\n"
				+ "aaaaaaaaaaaaaaabbbaaadddddddaa\n"
				+ "aaaaaaaaaaaaaaabbbaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaabbbbaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaabbbaaaaaaaaaaaaa\n"
				+ "aaaaaaaaaaaaaabbbaaaaaaaaaaaaa\n" + "---Tiles---\n" + "\n"
				+ "---Legend---\n" + "a = forest floor\n" + "b = river\n"
				+ "c = tree wall\n" + "d = cave wall\n" + "---Legend---\n"
				+ "\n" + "---Properties---\n" + "Description = Unknown Area\n"
				+ "FloorTile = 1\n" + "HashName = unknown\n" + "Level = 1\n"
				+ "MonsterType = IsHostile\n" + "WallTile = 10\n"
				+ "WanderingRate = 100\n" + "---Properties---\n" + "\n"
				+ "---Things---\n" + "12x7 [IsBandit]\n" + "13x7 [IsBandit]\n"
				+ "11x8 [IsBandit]\n" + "12x8 [IsBandit]\n"
				+ "14x8 [IsBandit]\n" + "23x8 [IsBandit]\n"
				+ "11x9 [IsBandit]\n" + "13x9 [IsBandit]\n"
				+ "20x9 barricade\n" + "21x9 barricade\n" + "24x9 [IsBandit]\n"
				+ "12x10 [IsBandit]\n" + "14x10 secret door\n"
				+ "16x10 [IsBandit]\n" + "18x10 [IsBandit]\n"
				+ "20x10 bandit archer\n" + "21x10 bandit archer\n"
				+ "23x10 locked door\n" + "   KeyName = copper key\n"
				+ "15x11 [IsBandit]\n" + "17x11 [IsBandit]\n"
				+ "19x11 secret door\n" + "16x12 invincible portcullis\n"
				+ "   KeyName = iron key\n" + "17x12 invincible portcullis\n"
				+ "   KeyName = ornate key\n" + "14x13 barricade\n"
				+ "15x13 bandit archer\n" + "25x13 locked door\n"
				+ "   KeyName = iron key\n" + "14x14 barricade\n"
				+ "15x14 bandit archer\n" + "29x15 barricade\n"
				+ "0x16 entrance point\n" + "15x16 [IsBandit]\n"
				+ "19x16 locked door\n" + "   KeyName = bronze key\n"
				+ "28x16 barricade\n" + "29x16 bandit archer\n"
				+ "15x17 [IsBandit]\n" + "28x17 barricade\n"
				+ "29x17 bandit archer\n" + "15x18 [IsBandit]\n"
				+ "29x18 barricade\n" + "14x19 locked door\n"
				+ "   KeyName = brass key\n" + "15x19 [IsBandit]\n"
				+ "26x19 locked door\n" + "   KeyName = copper key\n"
				+ "12x20 demon snake\n" + "11x21 warning point\n"
				+ "11x21 potion of literacy\n" + "12x21 lesser demon\n"
				+ "13x21 demon snake\n" + "12x22 demon vortex\n"
				+ "13x22 lesser demon\n" + "21x22 strong door\n"
				+ "   KeyName = iron key\n" + "18x24 bandit archer\n"
				+ "19x26 bandit archer\n" + "18x28 bandit archer\n"
				+ "---Things---\n");
		saved.put(
				"dwarftown",
				"---Tiles---\n"
						+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbaaaaaaabba\n"
						+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccadddddddddaaaabbbacccaaabba\n"
						+ "aaccccccccccccccccccacccacaccacccadcccccccdaaaaabbacccaabbba\n"
						+ "aaccccccccccccccccccaccccccccacccadcccccccdaaaaabbaaaaabbbba\n"
						+ "aaccaaccccccccccaaccacccacaaaacccadcccccccdaaaaaabbbaabbbbaa\n"
						+ "aaccaaccccccccccaaccaaaaaccccacccadcccccccdaaaaaabbbabbbbaaa\n"
						+ "aaccccccccccccccccccaccccccccacccaddddcddddaaaaaaabbbbbaaaaa\n"
						+ "aaccccccccccccccccccacccaccccacccaaaadcdaaaaaaaaaabbbbaaaaaa\n"
						+ "aaccaaccccccccccaaccaaaaaccccacccaddddcddddaaaaaaabbbbaaaaaa\n"
						+ "aaccaaccccccccccaaccacccacaaaacccadcccccccdaaaaaaabbbaaaaaaa\n"
						+ "aaccccccccccccccccccacccccaccacccadcccccccdaaaaaabbbbaaaaaaa\n"
						+ "aaccccccccccccccccccacccacaccccccadcccccccdaaaaaabbbaaaaaaaa\n"
						+ "aaccaaccccccccccaaccaacaaccccacccadcccccccdaaaaaabbbaaaaaaaa\n"
						+ "aaccaaccccccccccaaccacccacaccccccaddddcddddaaaaaabbbaaaaaaaa\n"
						+ "aaccccccccccccccccccacccacaccacccaaaadcdaaaaaaaaabbbaaaaaaaa\n"
						+ "aaccccccccccccccccccaaaaacaaaaccccccccccccccccccccccccccccca\n"
						+ "aaccaaccaaccaaccaaccacccaccccaccccccccccccccccccccccccccccca\n"
						+ "aaccaaccaaccaaccaaccaccccccccaccccccccccccccccccccccccccccca\n"
						+ "aaccccccccccccccccccacccaccccccccaaaaaaaaaaaaaaaaaabbbaaaaaa\n"
						+ "aaccccccccccccccccccacccaccccacccaaaaaaaaaaaaaaaaaabbbbaaaaa\n"
						+ "aaaaaaacaaccaacaaaaaacccaccccacccaaaaaaaaaaaaaaaaaaabbbbaaaa\n"
						+ "aaaaaaacaaccaacaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaaabbbbaaa\n"
						+ "aacccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaaabbbaaa\n"
						+ "accccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaaabbbaaa\n"
						+ "aacccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaaabbbaaa\n"
						+ "aaaaacaaacaaacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbaaa\n"
						+ "aaccccacccccacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbaaa\n"
						+ "aaccccacccccacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaa\n"
						+ "aaccccccccccacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbaaaa\n"
						+ "aaccccacccccacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaaa\n"
						+ "aaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaaaa\n"
						+ "aaccccacccccacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaaaaa\n"
						+ "aaccccacccccacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbaaaaaaa\n"
						+ "aaccccacccccacccaaaaaaaaaaacccccccccccccaccccaaaaabbaaaaaaaa\n"
						+ "aaaaaaaaacaaacccaaaaaaaaaaacccccccccccccaccccaaaabbaaaaaaaaa\n"
						+ "aacccaccccccccccaaaaaaaaaaacccccccccccccaccccaaabbbaaaaaaaaa\n"
						+ "aacccaccccccccccaaaaaaaaaaacccccccccccccaacaaaaabbbaaaaaaaaa\n"
						+ "aaccccccccaaacccaaaaaaaaaaacccccccccccccaccccaabbbaaaaaaaaaa\n"
						+ "aacccaccccacaccccccccccccccccccccccccccccccccaabbaaaaaaaaaaa\n"
						+ "aacccaccccacacccccccccccccccccccccccccccaccccaabbaaaaaaaaaaa\n"
						+ "aacaaaaaaaacacccccccccccccccccccccccccccaacaaabbbaaaaaaaaaaa\n"
						+ "accccaccccacacccccccccccccccccccccccccccaccccabbaaaaaaaaaaaa\n"
						+ "accccaccccacaaaaaaaaaaaaaaacccccccccccccaccccabbaaaaaaaaaaaa\n"
						+ "acccccccccacaccccaccccacccacccccccccccccaccccabbaaaaaaaaaaaa\n"
						+ "accccaccccacaccccaccccacccacccccccccccccaaacaabbaaaaaaaaaaaa\n"
						+ "accccaaaaaacaccccaccccacccacccccccccccccaccccabbaaaaaaaaaaaa\n"
						+ "accccaccccacaccccaccccacccacccccccccccccaccccabbaaaaaaaaaaaa\n"
						+ "acccccccccacaccccaccccacccaaaaaaaaacaaaaaccccabbaaaaaaaaaaaa\n"
						+ "accccaccccacaaaaaaaaaaacccccccacccccccccaaaaaabbaaaaaaaaaaaa\n"
						+ "accccaccccacaaaaaaaaaaacccccccacacacacacaaaaaabbaaaaaaaaaaaa\n"
						+ "aaaaaaaaaaacaaaaaaaaaaacccccccacccccccccaaaaaabbaaaaaaaaaaaa\n"
						+ "acccccccccacaaaaaaaaaaaaacaaaaacacccccacaaaaaabbaaaaaaaaaaaa\n"
						+ "acccccccccaaaaaaaaaaaaacccccccacccccccccaaaaabbbaaaaaaaaaaaa\n"
						+ "acceeeeeccaaaaaaaaaaaaacccccccacacacccacaaaaabbbaaaaaaaaaaaa\n"
						+ "acceeeeeccaaaaaaaaaaaaacccccccacccccccccaaaabbbaaaaaaaaaaaaa\n"
						+ "acceeeeeccaaaaaaaaaaaaacccccccacccacacacaaaabbbaaaaaaaaaaaaa\n"
						+ "acceeeeeccaaaaaaaaaaaaacccccccacccccccccaaabbbbaaaaaaaaaaaaa\n"
						+ "acccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaa\n"
						+ "acccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaaaaaaaaaaaaa\n"
						+ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaaaaaaaaaaaaa\n"
						+ "---Tiles---\n" + "\n" + "---Legend---\n"
						+ "a = stone wall\n" + "b = river\n"
						+ "c = stone floor\n" + "d = metal wall\n"
						+ "e = pool\n" + "---Legend---\n" + "\n"
						+ "---Properties---\n" + "Description = Dwarftown\n"
						+ "FloorTile = 1\n" + "Level = 10\n"
						+ "MonsterType = IsHostile\n" + "WallTile = 10\n"
						+ "WanderingRate = 20\n" + "---Properties---\n" + "\n"
						+ "---Things---\n" + "28x2 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "35x2 sovereign\n"
						+ "   Number = 1000\n" + "36x2 sovereign\n"
						+ "   Number = 1000\n" + "37x2 sovereign\n"
						+ "   Number = 1000\n" + "38x2 sovereign\n"
						+ "   Number = 1000\n" + "39x2 sovereign\n"
						+ "   Number = 1000\n" + "40x2 sovereign\n"
						+ "   Number = 1000\n" + "41x2 sovereign\n"
						+ "   Number = 1000\n" + "21x3 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "24x3 [IsDoor]\n"
						+ "26x3 [IsDoor]\n" + "28x3 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "35x3 sovereign\n"
						+ "   Number = 1000\n" + "36x3 sovereign\n"
						+ "   Number = 1000\n" + "37x3 sovereign\n"
						+ "   Number = 1000\n" + "38x3 sovereign\n"
						+ "   Number = 1000\n" + "39x3 sovereign\n"
						+ "   Number = 1000\n" + "40x3 sovereign\n"
						+ "   Number = 1000\n" + "41x3 sovereign\n"
						+ "   Number = 1000\n" + "51x3 secret door\n"
						+ "35x4 sovereign\n" + "   Number = 1000\n"
						+ "36x4 sovereign\n" + "   Number = 1000\n"
						+ "37x4 sovereign\n" + "   Number = 1000\n"
						+ "38x4 sovereign\n" + "   Number = 1000\n"
						+ "39x4 sovereign\n" + "   Number = 1000\n"
						+ "40x4 sovereign\n" + "   Number = 1000\n"
						+ "41x4 sovereign\n" + "   Number = 1000\n"
						+ "31x5 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "35x5 sovereign\n" + "   Number = 1000\n"
						+ "36x5 sovereign\n" + "   Number = 1000\n"
						+ "37x5 sovereign\n" + "38x5 sovereign\n"
						+ "   Number = 1000\n" + "39x5 sovereign\n"
						+ "   Number = 1000\n" + "40x5 sovereign\n"
						+ "   Number = 1000\n" + "41x5 sovereign\n"
						+ "   Number = 1000\n" + "21x6 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "22x6 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "24x6 [IsDoor]\n"
						+ "38x6 invincible portcullis\n"
						+ "   KeyName = skull key\n"
						+ "38x8 invincible portcullis\n"
						+ "   KeyName = dull key\n" + "31x9 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "21x10 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "24x10 [IsDoor]\n"
						+ "28x11 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "29x11 invincible portcullis\n"
						+ "   KeyName = copper key\n"
						+ "31x11 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "22x12 [IsDoor]\n" + "26x12 [IsDoor]\n"
						+ "28x12 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "22x13 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "28x13 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "29x13 invincible portcullis\n"
						+ "   KeyName = golden key\n"
						+ "22x14 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "22x17 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "24x17 [IsDoor]\n" + "26x17 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "29x18 [IsDoor]\n"
						+ "7x21 trapped black door\n"
						+ "   KeyName = dull key\n" + "10x21 ornate door\n"
						+ "   KeyName = ornate key\n" + "11x21 ornate door\n"
						+ "   KeyName = brass key\n"
						+ "14x21 trapped black door\n"
						+ "   KeyName = copper key\n" + "1x23 entrance point\n"
						+ "5x23 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "6x23 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "14x23 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "15x23 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "16x23 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "17x23 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "17x24 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "9x25 unbreakable door\n"
						+ "   KeyName = bronze key\n" + "3x27 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "6x28 invincible portcullis\n"
						+ "   KeyName = ornate key\n"
						+ "32x36 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "14x37 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "35x37 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "14x38 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "25x39 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "26x39 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "27x39 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "28x39 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "37x41 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "37x41 dwarf clansman\n" + "33x42 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "45x46 secret door\n"
						+ "34x51 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "37x52 dwarf clansman\n" + "   AIMode = Attack\n"
						+ "   TargetX = 0\n" + "   TargetY = 0\n"
						+ "31x53 invincible portcullis\n"
						+ "   KeyName = iron key\n"
						+ "33x53 invincible portcullis\n"
						+ "   KeyName = iron key\n" + "37x53 dwarf clansman\n"
						+ "   AIMode = Attack\n" + "   TargetX = 0\n"
						+ "   TargetY = 0\n" + "34x54 invincible portcullis\n"
						+ "   KeyName = ornate key\n"
						+ "34x56 invincible portcullis\n"
						+ "   KeyName = bronze key\n" + "---Things---\n");
		saved.put("karrain", "---Tiles---\n" + "aaaaaaaaaaaaaabbbccc\n"
				+ "adaaaaaaaaaaaabbbbac\n" + "adaaaeebeaaaaccbbbac\n"
				+ "adddeecbeeacccccbbbc\n" + "aaeedcbbeeaccccccbbb\n"
				+ "addebbbbbeacccecccbb\n" + "aaddebbbbeeeeeeeedbb\n"
				+ "aaedebbbbeeeeeeeeedb\n" + "aaaeeeebbeceeeeeeaab\n"
				+ "aaaaaeeeeeeeeeeddaab\n" + "accaaaaaeeeeeebbbbbb\n"
				+ "eecaaaeeeebbbbbcbbbb\n" + "aeeeeeeeeeeeeecceebb\n"
				+ "aaeccaaaeeeeeeeeeebb\n" + "aaaaaccccecceeeeeebb\n"
				+ "aaaacccccaeceeeeeebb\n" + "aaaacccccaaeeeeeeebb\n"
				+ "aaaacccccaaceeebebbb\n" + "aaaaaccaaaccebbbbbbb\n"
				+ "aaaaaaaaaabbbbbbbbbb\n" + "---Tiles---\n" + "\n"
				+ "---Legend---\n" + "a = mountains\n" + "b = sea\n"
				+ "c = forests\n" + "d = hills\n" + "e = plains\n"
				+ "---Legend---\n" + "\n" + "---Properties---\n"
				+ "Description = North Karrain Valley\n" + "FloorTile = 1\n"
				+ "IsWorldMap = 1\n" + "Level = 1\n"
				+ "MonsterType = IsHostile\n" + "VisionRange = 4\n"
				+ "WallTile = 10\n" + "WanderingRate = 0\n"
				+ "---Properties---\n" + "\n" + "---Things---\n"
				+ "1x1 dwarftown\n" + "6x2 goblin village\n" + "19x2 town\n"
				+ "13x3 ruin\n" + "13x7 tutorial inn\n" + "3x8 caves\n"
				+ "13x9 town\n" + "0x11 annenvale\n" + "2x13 graveyard\n"
				+ "10x15 town\n" + "6x16 dark forest\n" + "13x17 town\n"
				+ "---Things---\n");
	}
}
